title: At Dawncoffee
email: at@blogs.dawncoffee.com
url: "https://at.dawncoffee.com"
description: "Comunicaciones de Dawncoffee"

global:
 name: Dawncoffee
 google_analytics: UA-27136290-2

links:
 blog: "http://dawncoffee.com"
 twitter: "dawncoffeecom"
 disqus: "atdawncoffeecom"
 feed: "http://feeds.dawncoffee.com/dawncoffee/at"
 
markdown: kramdown
permalink: pretty
highlighter: pygments

sass:
  style: compressed
