title: At Dawncoffee
email: at@blogs.dawncoffee.com
url: "https://at.dawncoffee.com"
description: "Comunicaciones e informaciones de Dawncoffee."

global:
 name: Dawncoffee

links:
 blog: "http://dawncoffee.com"
 twitter: "dawncoffeecom"
 disqus: "atdawncoffeecom"
 feed: "http://feeds.dawncoffee.com/dawncoffee/at"

markdown: kramdown
permalink: pretty
highlighter: pygments

sass:
  compressed: true
